"""
AI Radio Station — Voice / DJ Layer (Phase 2 Completion)

Two-tier voice system:

1. **Default (always works)**: Browser Web Speech API (`speechSynthesis`).
   Instant, zero setup, decent quality.

2. **Premium (when enabled)**: Real audio generated by a local Piper instance
   via the official `rhasspy/wyoming-piper` HTTP endpoint. Much more natural.

The server prefers real audio clips when Piper is healthy. The client will
always fall back to browser speech if no audio file is provided.
"""
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, Optional
import hashlib
import wave
import io

import httpx

from config import (
    VOICOVER_CACHE_DIR,
    PIPER_URL,
    PIPER_VOICE,
    TTS_PROVIDER,
)


@dataclass
class VoiceClip:
    """Something the DJ should say."""
    text: str
    # If set and the file exists, the client should play this WAV instead of using speechSynthesis.
    path: Optional[Path] = None
    duration: float = 0.0


class TTSProvider(Protocol):
    def synthesize(self, text: str) -> VoiceClip: ...
    def is_healthy(self) -> bool: ...


class BrowserSpeechProvider:
    """Always returns a text-only clip. The client will use speechSynthesis."""
    def synthesize(self, text: str) -> VoiceClip:
        return VoiceClip(text=text, duration=self._estimate_duration(text))

    def is_healthy(self) -> bool:
        return True  # Browser speech is always "available"

    def _estimate_duration(self, text: str) -> float:
        words = len(text.split())
        return max(1.6, words / 2.6)


class PiperProvider:
    """
    Talks to a running rhasspy/wyoming-piper container.

    The stock image exposes a very simple HTTP API on port 5000:
        GET  /?text=Hello%20world
        POST /   (body = plain text)

    Both return raw WAV audio.
    """

    def __init__(self, base_url: str, voice: str | None = None, timeout: float = 20.0):
        self.base_url = base_url.rstrip("/")
        self.voice = voice
        self.timeout = timeout
        self._healthy: bool | None = None

    def is_healthy(self) -> bool:
        if self._healthy is not None:
            return self._healthy

        try:
            # Quick test with a very short phrase
            resp = httpx.get(
                f"{self.base_url}/",
                params={"text": "test"},
                timeout=5.0,
            )
            self._healthy = resp.status_code == 200 and len(resp.content) > 1000
        except Exception:
            self._healthy = False

        return self._healthy

    def synthesize(self, text: str) -> VoiceClip:
        if not self.is_healthy():
            # Let the caller fall back
            return VoiceClip(text=text, duration=self._estimate_duration(text))

        h = hashlib.md5(text.encode()).hexdigest()[:12]
        out_path = VOICOVER_CACHE_DIR / f"piper_{h}.wav"

        if out_path.exists() and out_path.stat().st_size > 2000:
            duration = self._get_wav_duration(out_path)
            return VoiceClip(text=text, path=out_path, duration=duration)

        try:
            params = {"text": text}
            if self.voice:
                params["voice"] = self.voice

            resp = httpx.get(
                f"{self.base_url}/",
                params=params,
                timeout=self.timeout,
            )
            resp.raise_for_status()

            if len(resp.content) < 2000:
                raise RuntimeError("Piper returned suspiciously small audio")

            out_path.write_bytes(resp.content)
            duration = self._get_wav_duration(out_path)
            return VoiceClip(text=text, path=out_path, duration=duration)

        except Exception as e:
            print(f"[voice] Piper synthesis failed: {e}")
            self._healthy = False  # force re-check next time
            return VoiceClip(text=text, duration=self._estimate_duration(text))

    def _get_wav_duration(self, path: Path) -> float:
        try:
            with wave.open(str(path), "rb") as wf:
                frames = wf.getnframes()
                rate = wf.getframerate()
                return frames / float(rate)
        except Exception:
            return self._estimate_duration("")

    def _estimate_duration(self, text: str) -> float:
        words = len(text.split())
        return max(1.6, words / 2.6)


class VoiceService:
    """High-level DJ voice manager with automatic fallback."""

    def __init__(self):
        self.providers: list[TTSProvider] = [BrowserSpeechProvider()]

        # Only try Piper if the user explicitly wants it
        if TTS_PROVIDER in ("piper", "auto"):
            piper = PiperProvider(
                base_url=PIPER_URL,
                voice=PIPER_VOICE,
            )
            if piper.is_healthy():
                # Put Piper first so it is preferred
                self.providers.insert(0, piper)
                print("[voice] Piper detected and healthy — using for DJ voiceovers")
            else:
                print("[voice] Piper not reachable — falling back to browser speech synthesis")

    def _get_clip(self, text: str) -> VoiceClip:
        for provider in self.providers:
            clip = provider.synthesize(text)
            if clip.path and clip.path.exists():
                return clip
        # Final fallback — always return something
        return VoiceClip(text=text, duration=3.0)

    # === Public API used by the rest of the radio ===

    def generate_station_id(self) -> VoiceClip:
        texts = [
            "You're tuned to Beacon FM — your personal archive of AI-generated music.",
            "This is Beacon FM, playing the complete works of artificial intelligence, without repetition.",
            "Beacon FM — where every track was born from imagination and code.",
        ]
        import random
        return self._get_clip(random.choice(texts))

    def generate_title_callout(self, title: str, artist: str = "AI") -> VoiceClip:
        text = f"Now playing: {title}."
        return self._get_clip(text)

    def generate_transition(self) -> VoiceClip:
        texts = [
            "Coming up next on the station.",
            "Another original composition, right after this.",
            "Continuing our journey through the archive.",
        ]
        import random
        return self._get_clip(random.choice(texts))

    def is_premium_voice_available(self) -> bool:
        return any(
            isinstance(p, PiperProvider) and p.is_healthy()
            for p in self.providers
        )


# Singleton used by main.py
voice_service = VoiceService()
